GET http://localhost:3000
### Get all travels
GET http://localhost:3000/api/travels
Content-Type: application/json

### Add a new travel
POST http://localhost:3000/api/travels
Content-Type: application/json
{
      "title": "aaaa",
      "image": "./images/travels/Khuvsgul lake.jpg",
      "type": "Соёлын аялал",
      "start_date": "2024-08-15",
      "finish_date": "2024-08-18",
      "days": 3,
      "price": 300000,
      "status": "Боломжтой",
      "location": "Орхон",
      "season": "Намар",
      "age_group": "Том хүн",
      "service_type": "Гидтай",
      "package_features": "Энгийн",
      "child_friendly": false
}

GET http://localhost:3000/api/bookings
Content-Type: application/json

POST http://localhost:3000/api/bookings
Content-Type: application/json
{
  "user_id": 13,
  "travel_id": 10,
  "date": "2025-01-05",
  "status": "In Progress",
  "number_of_travelers": 2,
  "total_price": 300000
}

GET http://localhost:3000/api/destinations
Content-Type: application/json

GET http://localhost:3000/api/users
Content-Type: application/json

POST http://localhost:3000/api/users/register
Content-Type: application/json
{
  "full_name": "tamir",
  "email": "tamiraa@gmail.com",
  "password": "1345678",
  "phone_number": "90678969",
  "date_of_birth": "1995-05-01",
  "gender": "male"
}

POST http://localhost:3000/api/users/login
Content-Type: application/json

{
  "email": "aaaa@gmail.com",
  "password": "1345678"
}

DELETE http://localhost:3000/api/users/34
Content-Type: application/json
